---
title: "SDiD Simulations"
author: "Benjamin Herzberger"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
#rm(list=ls())
source("Functions.R")

# Set up estimators to be used in the process
estimators = list(did=did_estimate, sc=sc_estimate, sdid=synthdid_estimate)

# Set seed for replicability
set.seed(100)

# Draw random number between 1 and 1000 (number of iterations)
index <- round(runif(1, 1, 1000)) # will be used to select one simulation for visualization

# Set up relative path for working directory
path <- "C:/Users/benny/OneDrive/Studium/Tübingen/DS in B&E/4. Semester SS2024/B520 Research Seminar on Marketing/Code"
```


# Estimation of Causal effects using simulated data and DiD, SC and SDiD

### Assessing the effect of number of pre-treatment periods
```{r}
# For this, we use a sufficiently large number of treated, as well as control units 
# This analysis is performed first, because we can then select the minimum number
# of required pre-treatment periods for the analysis of very large sample sizes
# to save some time. 

N <- 90
T <- 10
n_treated <- 10
pre_control_trend <- 0.1
pre_treated_trend <- 0.1
post_control_trend <- 0.1
post_treated_trend <- 0.1
treatment_effect <- 2
iterations <- 1000

# Setting a lower value than 3 is not possible 
treatment_periods = c(3, 4, 5, 6, 7, 8, 9, 10)

for(treatment_period in treatment_periods){
  simulation_params <- list(N = N, T = T, n_treated = n_treated, treatment_period = treatment_period,
                           pre_control_trend = pre_control_trend, pre_treated_trend = pre_treated_trend,
                           post_control_trend = post_control_trend, post_treated_trend = post_treated_trend,
                           treatment_effect = treatment_effect)
  # Simulation & estimation
  results <- repeated_simulation(simulation_function = treatment_simulation,
                                     simulation_params = simulation_params, iterations = iterations)
  estimates <- results$estimates
  df <- results$dfs[[index]]
  
  write.csv(df, paste0(path, "/Output/Data/df_treatment_period_", treatment_period, ".csv"))
  write.csv(estimates, paste0(path, "/Output/Data/estimates_treatment_period_", treatment_period,".csv"))
  
  plot_estimates(estimates) %>%
    ggsave(filename = paste0(path, "/Output/Plots/estimates_plot_treatment_period_", treatment_period, ".png"), width = 10, height = 5, units = "in", dpi = 300)
  plot_grouped_simulations(results$dfs) %>%
    ggsave(filename = paste0(path, "/Output/Plots/data_plot_treatment_period", treatment_period, ".png"), width = 10, height = 5, units = "in", dpi = 300)
}
```


### Assessing the effect of number of treated and control units
```{r}
# Additional parameters
# Number of treated units is designed to always be 20% of the number of control units
# to ensure comparability across simulations.
N <- c(5, 10, 50, 100, 500, 1000, 5000)
n_treated <- c(1, 2, 10, 20, 100, 200, 1000)

for(i in 1:length(N)){
  simulation_params <- list(N = N[i], T = T, n_treated = n_treated[i], treatment_period = treatment_period,
                           pre_control_trend = pre_control_trend, pre_treated_trend = pre_treated_trend,
                           post_control_trend = post_control_trend, post_treated_trend = post_treated_trend,
                           treatment_effect = treatment_effect)
  # Simulation & estimation
  results <- repeated_simulation(simulation_function = treatment_simulation,
                                     simulation_params = simulation_params, iterations = iterations)
  estimates <- results$estimates
  df <- results$dfs[[index]]
  
  write.csv(df, paste0(path, "/Output/Data/df_N_", N[i], "_n_treated_", n_treated[i], ".csv"))
  write.csv(estimates, paste0(path, "/Output/Data/estimates_N_", N[i], "_n_treated_", n_treated[i], ".csv"))
  
  plot_estimates(estimates) %>%
    ggsave(filename = paste0(path, "/Output/Plots/estimates_plot_N_", N[i], "_n_treated_", n_treated[i], ".png"), width = 10, height = 5, units = "in", dpi = 300)
  plot_grouped_simulations(results$dfs) %>%
    ggsave(filename = paste0(path, "/Output/Plots/data_plot_N_", N[i], "_n_treated_", n_treated[i], ".png"), width = 10, height = 5, units = "in", dpi = 300)
}
  print(paste0("Finished simulation for N = ", N[i], " and n_treated = ", n_treated[i]))
```


### Assessing the effect of very large number of treated and control units
```{r}
# Set T and treatment period to lowest possible value

T <- 3
treatment_period <- 3
N <- c(10000, 50000, 100000, 500000, 1000000, 3000000)
n_treated <- c(2000, 10000, 20000, 100000, 200000, 600000)

for(i in 1:length(N)){
  simulation_params <- list(N = N[i], T = T, n_treated = n_treated[i], treatment_period = treatment_period,
                           pre_control_trend = pre_control_trend, pre_treated_trend = pre_treated_trend,
                           post_control_trend = post_control_trend, post_treated_trend = post_treated_trend,
                           treatment_effect = treatment_effect)
  # Simulation & estimation
  results <- repeated_simulation(simulation_function = treatment_simulation,
                                     simulation_params = simulation_params, iterations = iterations)
  estimates <- results$estimates
  df <- results$dfs[[index]]
  
  write.csv(df, paste0(path, "/Output/Data/df_N_", N[i], "_n_treated_", n_treated[i], ".csv"))
  write.csv(estimates, paste0(path, "/Output/Data/estimates_N_", N[i], "_n_treated_", n_treated[i], ".csv"))
  
  plot_estimates(estimates) %>%
    ggsave(filename = paste0(path, "/Output/Plots/estimates_plot_N_", N[i], "_n_treated_", n_treated[i], ".png"), width = 10, height = 5, units = "in", dpi = 300)
  plot_grouped_simulations(results$dfs) %>%
    ggsave(filename = paste0(path, "/Output/Plots/data_plot_N_", N[i], "_n_treated_", n_treated[i], ".png"), width = 10, height = 5, units = "in", dpi = 300)
}
  print(paste0("Finished simulation for N = ", N[i], " and n_treated = ", n_treated[i]))
```


### Simulation with violation of parallel trend assumption
```{r}



```